Repository EJMontes9/Amazin, pull requests merged in 2022-07, with the labels that each got.

#26 Detalles
  src/app/Components/product-details/product-details.component.css
  src/app/Components/product-details/product-details.component.html
  src/app/Components/product-details/product-details.component.spec.ts
  src/app/Components/product-details/product-details.component.ts
  src/app/app.module.ts
Labels: Prioridad: Alta, FrontEnd, developer

#28 ContactUs
  src/app/Components/contac-us/contac-us.component.css
  src/app/Components/contac-us/contac-us.component.html
  src/app/Components/contac-us/contac-us.component.spec.ts
  src/app/Components/contac-us/contac-us.component.ts
  src/app/Components/footer/footer.component.html
  src/app/Components/header/header.component.html
  src/app/Components/login/login.component.html
  src/app/Components/login/login.component.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
Labels: FrontEnd, developer

#29 Erick
  src/app/Components/header/header.component.html
  src/app/Components/header/header.component.ts
  src/app/Components/login/login.component.html
  src/app/Components/product-filter/product-filter.component.css
  src/app/Components/product-filter/product-filter.component.html
  src/app/Components/product-filter/product-filter.component.spec.ts
  src/app/Components/product-filter/product-filter.component.ts
  src/app/Components/register/register.component.html
  src/app/app.component.html
  src/app/app.module.ts
Labels: developer

#27 Recursos de pay
  src/app/Components/purchasing-process/purchasing-process.component.css
  src/app/Components/purchasing-process/purchasing-process.component.html
  src/app/Components/purchasing-process/purchasing-process.component.spec.ts
  src/app/Components/purchasing-process/purchasing-process.component.ts
  src/app/app.component.html
  src/app/app.module.ts
Labels: FrontEnd, developer
